# Generated by Django 3.0.6 on 2020-05-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('mess', 'Mess'), ('sports', 'Sports'), ('student_affairs', 'Student affairs'), ('hostel', 'Hostel'), ('security', 'Security'), ('guest_house', 'Guest House'), ('library', 'Library'), ('other', 'Other')], default='other', max_length=18),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('comlpeted', 'Completed'), ('closed', 'Closed')], default='reported', max_length=15),
        ),
    ]
