# Generated by Django 3.0.6 on 2020-05-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20200509_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
