# Generated by Django 3.0.6 on 2020-05-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20200509_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='text',
            new_name='description',
        ),
    ]
