# Generated by Django 3.0.2 on 2020-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_profile_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
