# Generated by Django 3.0.6 on 2020-05-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_auto_20200512_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
