# Generated by Django 3.0.6 on 2020-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_complaint_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='head_of',
            field=models.CharField(choices=[('academic', 'Academic'), ('mess', 'Mess'), ('sports', 'Sports'), ('student_affairs', 'Student affairs'), ('hostel', 'Hostel'), ('security', 'Security'), ('guest_house', 'Guest House'), ('library', 'Library'), ('other', 'Other')], default='', max_length=18),
        ),
    ]
