# Generated by Django 4.0.1 on 2022-01-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_profile_head_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remark',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
